config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root 'welcome#index'

  # Example of regular route:
  get 'login' => 'login#index'
  get 'feed' => 'facebook#feed'
  post 'status' => 'facebook#status'
  get 'stocks' => 'stocks#index'
  get 'stocks/stock' => 'stocks#stock'
  #stock transaction button links to the stock_transaction method in the controller
  #post "stocks/stock" => "stocks#stock_transaction"
  match "stocks/stock" => "stocks#stock", via: :post
  get 'stocks/data'
  get 'calendar' => 'calendar#index'
  get 'events' => 'events#index'
  get 'downloadMessage' => 'messages#download', :defaults => { :format => 'txt' }

  resources :events

  # Facebook callback
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :message, presence: true, length: {minimum: 3 }
  belongs_to :user


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    #if there is a user logged in
    if current_user != nil
      #only load all of the chat messages since the user last logged in
      @messages = Message.where("updated_at >= ?", current_user.updated_at)
    end
    render json: @messages.to_json(except: [:id, :created_at, :updated_at, :user_id], include: {:user => {:only => :name}})
  end

  def download
    @messages = Message.all
    #if there is a user logged in
    if current_user != nil
      #only load all of the chat messages since the user last logged in
      @messages = Message.where("updated_at >= ?", current_user.updated_at)
    end


    respond_to do |format|
      format.text { send_data @messages.to_json(except: [:id, :created_at, :updated_at, :user_id], include: {:user => {:only => :name}}),type: :json, disposition: "attachment" }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show

  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id=current_user.id

    respond_to do |format|
      if @message.save
        format.js { render nothing: true }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      @message.user_id=current_user.id
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message, :user_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.message %></td>
        <td><%= message.user.name %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user.name %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>