config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root 'welcome#index'

  # Example of regular route:
  get 'login' => 'login#index'
  get 'feed' => 'facebook#feed'
  post 'status' => 'facebook#status'
  get 'stocks' => 'stocks#index'
  get 'stocks/stock' => 'stocks#stock'
  #stock transaction button links to the stock_transaction method in the controller
  #post "stocks/stock" => "stocks#stock_transaction"
  match "stocks/stock" => "stocks#stock", via: :post
  get 'stocks/data'
  get 'calendar' => 'calendar#index'
  get 'events' => 'events#index'
  get 'downloadMessage' => 'messages#download', :defaults => { :format => 'txt' }

  resources :events

  # Facebook callback
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :between, lambda {|start_time, end_time|
                  {:conditions => ["? < starts_at < ?", Event.format_date(start_time), Event.format_date(end_time)] }
                }

  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
        :id => self.id,
        :title => self.title,
        :description => self.description || "",
        :start => starts_at.rfc822,
        :end => ends_at.rfc822,
        :allDay => self.all_day,
        :recurring => false,
        :url => Rails.application.routes.url_helpers.event_path(id),
        #:color => "red"
    }

  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @events = Event.between(params['start'], params['end']) if (params['start'] && params['end'])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(user_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  def user_params
    params.require(:event).permit(:title, :starts_at, :ends_at, :all_day, :description )
  end
  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(user_params)
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :all_day %><br />
    <%= f.check_box :all_day %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>All day</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.all_day %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Starts at:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @event.ends_at %>
</p>

<p>
  <b>All day:</b>
  <%= @event.all_day %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', calendar_path %>